language: php

php:
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache
          
matrix:
  fast_finish: true
  include:
    - php: 7.0 # Laravel 5.0 requires Mcrypt, but it is deprecated as of PHP 7.1
      env: ILLUMINATE_VERSION=5.0.* TESTBENCH_VERSION=3.0.* PHPUNIT_VERSION=4.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.1.* TESTBENCH_VERSION=3.1.* PHPUNIT_VERSION=5.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.2.* TESTBENCH_VERSION=3.2.* PHPUNIT_VERSION=5.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.3.* TESTBENCH_VERSION=3.3.* PHPUNIT_VERSION=5.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.4.* TESTBENCH_VERSION=3.4.* PHPUNIT_VERSION=5.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.5.* TESTBENCH_VERSION=3.5.* PHPUNIT_VERSION=6.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.6.* TESTBENCH_VERSION=3.6.* PHPUNIT_VERSION=7.*

sudo: false

before_install:
  # Disable XDebug to speed up Composer.
  - cp $HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini /tmp
  - phpenv config-rm xdebug.ini
  # Require a specific Illuminate version.
  - if [ -n "$ILLUMINATE_VERSION" ] ; then composer require illuminate/support:${ILLUMINATE_VERSION} illuminate/validation:${ILLUMINATE_VERSION} --no-update; fi
  - if [ -n "$TESTBENCH_VERSION" ] ; then composer require orchestra/testbench:${TESTBENCH_VERSION} --no-update; fi
  - if [ -n "$PHPUNIT_VERSION" ] ; then composer require phpunit/phpunit:${PHPUNIT_VERSION} --no-update; fi
  
install:
  - travis_wait 60 travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  # Show some package versions
  - composer show laravel/framework
  - composer show orchestra/testbench
  - composer show phpunit/phpunit
  
script:
  # Re-enable XDebug.
  - phpenv config-add /tmp/xdebug.ini
  # Run the tests.
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  # Send test results to Scrutinizer.
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
